# prompt segments
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context root_indicator_joined dir dir_writable vcs)
POWERLEVEL9K_DISABLE_RPROMPT=true
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)


# context
DEFAULT_USER="$USER"
POWERLEVEL9K_CONTEXT_TEMPLATE=%n@%m

# dir
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

